name : Echo

on:
    push:
          branches : ["main"]
    
jobs:
      build:
            runs-on: ubuntu-latest

            steps:
               - name: Checkout repository
                 uses: actions/checkout@v2
      build2:
            runs-on: ubuntu-latest

            steps:
               - name: Checkout repository
                 uses: actions/checkout@v2
